parameters:
#    craft_api.example.class: Craft\ApiBundle\Example

services:
#    craft_api.example:
#        class: %craft_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
