imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    http_method_override: true
    translator: ~
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~ # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [MopaBootstrapBundle, CraftLocationBundle, FOSCommentBundle]
    filters:
      #  less: 
      #    node: /usr/local/bin/node
      #    node_paths: [/usr/local/share/npm/lib/node_modules]
      #    apply_to: "\.less$"
        sass:
          sass: /usr/bin/compass
          apply_to: "\.(scss|sass)$"
        yui_js:
          jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_css:
          jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
          apply_to: "\.css$"
        cssrewrite: ~
        
# Doctrine connection
doctrine_mongodb:
   connections:
     default: 
       server: "%mongodb_host%"
       options: "%mongodb_options%"
   default_database: "%mongodb_database%"
   document_managers:
     default:
       auto_mapping: true
   auto_generate_hydrator_classes: true 
#ACL MongoDB Connection
iam_persistent_mongo_db_acl:
    acl_provider:
        default_database: %mongodb_database%
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
fos_user:
  db_driver: mongodb
  firewall_name: main
  user_class: Craft\UserBundle\Document\User
#rest API
fos_comment:
  db_driver: mongodb
  class:
    model:
      comment: Craft\LocationBundle\Document\Comment
      thread: Craft\LocationBundle\Document\Thread
fos_rest:
  routing_loader:
    default_format: json
  view:
    formats:
      rss: true
      xml : true
      json: true
    templating_formats:
      html: false

mopa_bootstrap:
  navbar: ~
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text: ~
        sonata.block.service.rss: ~
services: 
  location_service:
    class: Craft\LocationBundle\Services\Location
    arguments: [%distance_unit%, @doctrine_mongodb.odm.document_manager, @security.acl.provider]
    
