imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trust_proxy_headers: false # Whether or not the Request object should trust proxy headers (X_FORWARDED_FOR/HTTP_CLIENT_IP)
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [MopaBootstrapBundle]
    filters:
        less: 
          node: /usr/local/bin/node
          node_paths: [/usr/local/share/npm/lib/node_modules]
          apply_to: "\.less$"
        cssrewrite: ~
        
# Doctrine connection
doctrine_mongodb:
   connections:
     default: 
       server: "%mongodb_host%"
       options: "%mongodb_options%"
   default_database: "%mongodb_database%"
   document_managers:
     default:
       auto_mapping: true
   auto_generate_hydrator_classes: true 
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
fos_user:
  db_driver: mongodb
  firewall_name: main
  user_class: Craft\UserBundle\Document\User

mopa_bootstrap:
  navbar: ~